service:
  name: poc
  identifier: poc
  orgIdentifier: default
  projectIdentifier: default_project
  serviceDefinition:
    spec:
      artifacts:
        primary:
          primaryArtifactRef: dockerhub
          sources:
            - spec:
                connectorRef: dockerhub
                imagePath: sankaranarayananmurali/maven-v1
                tag: <+input>
                digest: ""
              identifier: dockerhub
              type: DockerRegistry
      manifests:
        - manifest:
            identifier: service
            type: K8sManifest
            spec:
              store:
                type: Github
                spec:
                  connectorRef: mavengithubconnector
                  gitFetchType: Branch
                  paths:
                    - maven-barista/k8s /service.yaml
                  branch: master
              skipResourceVersioning: false
              enableDeclarativeRollback: false
              optionalValuesYaml: false
    type: Kubernetes
