apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-barista
  template:
    metadata:
      labels:
        app: maven-barista
    spec:
      containers:
        - name: maven-barista
          image: <+artifact.image>
          ports:
            - containerPort: 8080
